//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condition
    {
        public Condition()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int ConditionID { get; set; }
        public string ConditionName { get; set; }
    
        public virtual ICollection<Task> Task { get; set; }
    }
}
