//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Project = new HashSet<Project>();
            this.Task = new HashSet<Task>();
            this.Task1 = new HashSet<Task>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public int EmployeeRoleID { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
    
        public virtual EmployeeRole EmployeeRole { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<Task> Task { get; set; }
        public virtual ICollection<Task> Task1 { get; set; }
    }
}
