//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySuperDuperProjectEntities : DbContext
    {
        public MySuperDuperProjectEntities()
            : base("name=MySuperDuperProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Condition> Condition { get; set; }
        public DbSet<Project> Project { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Task> Task { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<EmployeeRole> EmployeeRole { get; set; }
    }
}
