//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public int ConditionID { get; set; }
        public int StatusID { get; set; }
        public int AuthorID { get; set; }
        public int AssignedToID { get; set; }
        public int ProjectID { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
        public virtual Employee Author { get; set; }
        public virtual Employee AssignedTo { get; set; }
    }
}
