//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public int ConditionID { get; set; }
        public int StatusID { get; set; }
        public int AuthorID { get; set; }
        public int AssignedToID { get; set; }
        public int ProjectID { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
        public virtual User Author { get; set; }
        public virtual User AssignedTo { get; set; }
    }
}
