//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Project = new HashSet<Project>();
            this.Task = new HashSet<Task>();
            this.Task1 = new HashSet<Task>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public int UserRoleID { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<Task> Task { get; set; }
        public virtual ICollection<Task> Task1 { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
